<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */
?>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox] .price-wrapper": {
            "Infrangible_CatalogProductPriceCalculation/js/price-box-calculated": {}
        }
    }
</script>
