<?php

declare(strict_types=1);

use Infrangible\CatalogProductPriceCalculation\Block\Section;

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Section $block */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "catalog-product-price-calculation": {
                        "component": "Infrangible_CatalogProductPriceCalculation/js/section",
                        "calculations": <?= $block->getCalculationsConfig(); ?>
                    }
                }
            }
        }
    }
</script>
