<?php

declare(strict_types=1);

use Infrangible\CatalogProductPriceCalculation\Block\Product\Renderer\Listing\Bundle;
use Magento\Framework\Escaper;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Escaper $escaper */
/** @var Bundle $block */

$product = $block->getProduct();
?>

<?php if ($product && $product->isAvailable()): ?>
    <script type="text/x-magento-init">
        {
            "[data-role=priceBox][data-price-box=product-id-<?= $escaper->escapeJs($product->getId()); ?>]": {
                "priceBox": {
                    "priceConfig": <?= /* @noEscape */ $block->getPriceConfigJson(); ?>
                }
            }
        }
    </script>
<?php endif; ?>
